import NextHead from 'next/head'

export const Head: React.VFC = () => {
  return (
    <NextHead>
      <title>ReactHookForm Sample</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  )
}
